config/routes.rb
Rails.application.routes.draw do

  
  root 'pages#home'
  
  get 'about', to: 'pages#about'
  
  get 'blog', to: 'pages#blog'
  
      resources :articles
  
     get 'signup', to: 'users#new'
  
           
        resources :users, except: [:new]
  
      get 'login', to: 'sessions#new'
    
       post 'login', to: 'sessions#create'
      
      delete 'logout', to: 'sessions#destroy'
    
  
  resources :categories, except: [:destroy]
  
  

end

app/models/article.rb
class Article < ActiveRecord::Base 

#associates the article id with the user 
belongs_to :user

#each article can have many categories
has_many :article_categories
# has many categories through article categories
has_many :categories, through: :article_categories

#makes sure when you create an article it contains a title and a description.
#before a new article hits the database this ensures that it has an title, description
validates :title, presence: true, length: {minimum: 3, maximum: 50}

validates :description, presence: true, length: {minimum: 10, maximum: 300}

#makes sure each article has a user id present
validates :user_id, presence: true
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
 # the before actions run in order  
   #makes the set_article method from the bottom of the page(private) avaialble at the start of the 4 actions listed
   # the order of actions between [ ] is important, order them in the order you want them to execute
before_action :set_article, only: [:edit, :update, :show, :destroy]

 
 # require_user restricts controller actions to certain users 
 # require someone be logged in as a user, except for the index and show actions 
 #except for the index and show actions you need to be logged in 
 before_action :require_user,  except: [:index, :show]
 
 #this requires that it be the same user that created the article to edit, update and destroy it
 #require_same_use is in articles controller
 before_action :require_same_user, only: [:edit, :update, :destroy]

#Index shows a list of all the articles created, it needs an index.html.erb
#/articles***
    def index
        #grabs all articles in database
       # @articles = Article.all
       #by default this will only load 20 single @article per page
       @articles = Article.paginate(page: params[:page], per_page: 5)
    end 


#is the html page for entering and creating a new article. new.html.erb
#/articles/new***
    def new
        @article = Article.new
    end

#Create is what actually creates the new article from the new action. no html.erb
    def create
     
        @article = Article.new(article_params)
        
         #ensures article has a user - User.last
         @article.user =  current_user
       
        #redirect to articles controler, #show path with the @article
       # redirect_to article_path(@article)
        
        if @article.save
            #this flash is in the partial layouts/_messages.html.erb
            flash[:success] = "Article was succesfully created"
            redirect_to article_path(@article)
            
        else
            # this just re-renders a new template
            render 'new'
        end 
    end 

# Show - finds and shows a single article details using show.html.erb 
# articles/id***
    def show
      #finds articles based on their id and shows them in views/articles/show.html.erb
      # @article = Article.find(params[:id]) 
      
    end

# edit is the action that shows the individual article you want to edit. it has edit.html.erb
# articles/id/edit***
    def edit
       # @article = Article.find(params[:id])
       
    end 

#update is the action that actually updates the article with the new info from the edit action. it does not have an html.erb
    def update
      #@article = Article.find(params[:id])  
    
      if @article.update(article_params)
           #this flash is in the partial layouts/_messages.html.erb
          flash[:success] = "Article was succesfully updated"
          redirect_to article_path(@article)
      else
          render 'edit'
      end
    end 

    def destroy
        #@article = Article.find(params[:id])
        
        @article.destroy
         #this flash is in the partial layouts/_messages.html.erb
        flash[:danger] = "Article was succesfully deleted"
        redirect_to articles_path
    end




private

    def set_article
       @article = Article.find(params[:id]) 
    end
    
    def article_params
        #for the article (@article) object permit params title and description
                                                                #entering categories in the article form
        params.require(:article).permit(:title, :description, category_ids: [ ])
    end
    
    def require_same_user
        # != not equal to
        # if current user is not the creator of that article or an admin 
        if current_user != @article.user and !current_user.admin?
            flash[:danger] = "You can only edit or delete your own articles"
            redirect_to root_path
        end 
    end
    


end

app/views/articles/_article.html.erb
<!-- On pages with mutiple versions of an instance such as the index page, you use article, not @article to iteratte through mutiple-->
    
    <!--obj replaces @article and @user, so when the form is rendered in either controller it works-->
    <% obj.each do |article| %>
    
          
    <div class="row">
        <div class="col-xs-8 col-xs-offset-2">
           <div class="well well-lg">
           
            <div class="article-title">
                <!-- allows user to click on the article title text to go to the article page -->
                <%= link_to article.title, article_path(article) %>
            </div>
           
            <div class="article-body">
                <!-- limits the characters shown in the description section to 100 characters-->
                <%= truncate(article.description, length: 100) %>
                
              
            </div>
            
             <div class="article-meta-details">
                <small>Created by: <%= article.user.username  if article.user %>,
                                    <%= time_ago_in_words(article.created_at) %> 
                go, last updated:    <%= time_ago_in_words(article.updated_at)  %> ago
                </small>
                </div>
          
            <% if article.categories.any?  %>
                    <p>Categories: <%= render article.categories %></p>
            <% end %>
            
            
            
            
            <!-- We want to resturct edit and delete actions only to logged in users that created the 
                   || means OR
                   
                   allows theses actions if it is the current user or the admin
            -->
                <%  if logged_in? && (current_user == article.user || current_user.admin?) %>
                      
                       <div class="article-actions">
                                    <%= link_to "Edit this Article", edit_article_path(article), class: "btn btn-xs btn-primary" %>
                                    <%= link_to "Delete Article", article_path(article), method: :delete, 
                                                                    data: {confirm: "are you sure you want to delete?"}, 
                                                                    class: "btn btn-xs btn-danger" %>
                        </div>
                    
                <%  end  %>
            
              </div>
        </div>
        
    </div>
   <% end %>

app/views/articles/_form.html.erb
<!-- obj: @article sets the obj to the article instance variable from the _errors partial in shared-->
<%= render 'shared/errors', obj: @article  %>


<!-- ARTICLE FORM-->
<div class="row">
    
<div class="col-md-12">
    
<%= form_for(@article, :html => {class: "form-horizontal", role: "form"}) do |f| %>

    <div class="form-group">
        <div class="control-label col-sm-2">
            <%= f.label :title %>
        </div>
        
        <div class="col-sm-8">
            <%= f.text_field :title, rows: 10, class: "form-control", placeholder: "Enter title" %>
        </div>
    </div>
    
    

    <div class="form-group">
        <div class="control-label col-sm-2">
            <%=  f.label :description %>
        </div>
        
         <div class="col-sm-8">
            <%=  f.text_area :description, rows:10, class: "form-control", placeholder: "Enter Body of article" %>
        </div>
    </div>

    <div class="form-group">
        <div class="row">
                <div class="col-sm-offset-2 col-sm-8">
                     <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
                             <% cb.label(class: "checkbox-inline input_checkbox") {cb.check_box(class: "checkbox") + cb.text }  %>
                     <% end %>
                </div>
        </div>
    </div>


    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
             <%= f.submit class: 'btn btn-primary btn-lg' %>
        </div>
    </div>
   

<% end %>
<!-- END ARTICLE FORM-->
<div class="col-xs-4 col-xs-offset-4">
    [ <%= link_to "Cancel Request and Return to listings", articles_path %> ]
</div>
</div>
</div>

app/views/articles/edit.html.erb
<h1 align="center">Edit <strong><%= @article.title %> </strong> Article</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1>All Listings</h1>

<div align="center">
    <%= will_paginate %>
</div>

<!-- obj: @articles refers to the obj being used in the _articles.html.erb partial-->
<%= render 'article', obj: @articles %>

<div align="center">
    <%= will_paginate %>
</div>


<%= link_to "Create New Article", new_article_path, class: "btn btn-lg btn-success" %>
<%= link_to "Home", root_path, class: "btn btn-sm btn-default" %>


    
  
    
    
    
    

app/views/articles/new.html.erb
<h1 align="center" >Create a New Article</h1>


<%= render 'form' %>

app/views/articles/show.html.erb
<h1>Title: <%= @article.title %></h1>



<div class="well col-xs-8 col-xs-offset-2">
    
   
    <!-- this block only runs if the article has a user, otherwise it discards everthing when showing an invdivduals article
        - only shows users information associated with the article if the article has a user
        - keeps it from blowing up if an article doesnt have an associated user
    -->
<% if @article.user %>   
             <!-- listing shows the info of the creator/user of the article - @article.user-->
            <ul class="listing">
            <div class="row center">
                <!--
                - uses @article.user and @article.user.username to display the user info associated with the article
                - copy/pasted from views/users/index.html.erb 
                -->
                <div class="col-md-4 col-md-offset-4">
                    <li>Created by:</li>
                    <!-- shows users gravatar picture, links to that users individual show page
                    put whole thing in brackets, then use if @article.user 
                    -->
                    <li><%= link_to gravatar_for(@article.user), user_path(@article.user) %></li>
                    <li class="article-title">
                        <!-- link displays the users username, and the path links to the users individual show page-->
                        <%= link_to @article.user.username, user_path(@article.user) %>
                    </li>
                    <!-- 
                    - shows the amount of articles the user has created
                    - if more then 1, pluralize puts an s on it
                    - if statement - only shows this number if users has articles
                    -->
                    <li><small><%= pluralize(@article.user.articles.count, "article") if @article.user.articles %>
                    </small></li>
                    
                </div>
            </div>
        </ul>
<% end %>
    
    
    
    
    <h4 class="center description"><strong>Description</strong></h4>
    <!-- simple format displays the with the spacing entered in the text box-->
   
   
    <%= simple_format(@article.description) %>
    <% if @article.categories.any? %>
    
    <p>Categories: <%= render @article.categories  %></p>
    
    <% end %>
     
     <div class="article-actions">
        
        <% if logged_in? && (current_user == @article.user || current_user.admin? ) %>
        
            <%= link_to "Edit this Article", edit_article_path(@article), class: "btn btn-xs btn-primary" %>
            
             <%= link_to "Delete Article", article_path(@article), method: :delete, 
                                            data: {confirm: "are you sure you want to delete?"}, 
                                            class: "btn btn-xs btn-danger" %>
            
           <% end %>
           
           <%= link_to "View All Articles", articles_path, class: "btn btn-xs btn-success"  %>
           
    </div>

     
</div>
   